#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --job-name=3Layer-Pythia_Arithmetic_nGPT
#SBATCH --time=04:30:00
#SBATCH --output=job_logs/3Layer-Pythia_Arithmetic_nGPT_%A.out

cd $HOME/Letting-NNs-Think
. jobs/environment.sh

srun python -m experiment \
    --model-name "EleutherAI/pythia-14m" \
    --dataset synthetic_arithmetic_task \
    --finetune-mode full \
    --enable-normalization \
    --remove-layers 0:3 \
    --batch-size 8192 \
    --eval-batch-size 32768
    --grad-acc-steps 1 \
    --learning-rate 1e-4 \
    --max-hours 4 \
    --max-epochs 25 \
    --max-training-steps 1000000 \
    --experiment-name 3Layer_Pythia_Arithmetic_nGPT \
    --save-to-checkpoint 3Layer_Pythia_Arithmetic_nGPT \
    --enable-logging \
    --mode train

srun python -m experiment \
    --model-name "EleutherAI/pythia-14m" \
    --dataset synthetic_arithmetic_task \
    --pretrained \
    --finetune-mode full \
    --enable-normalization \
    --remove_layers 0:3 \
    --experiment-name 3Layer_Pythia_Arithmetic_nGPT_Eval \
    --load-from-checkpoint 3Layer_Pythia_Arithmetic_nGPT \
    --evaluation-metrics arithmetic_task \
    --mode evaluate \
    --max-epochs 1 \
    --max-training-steps 1 \
    --eval-batch-size 32768 \
    --enable-logging
