#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --job-name=Pythia_Arithmetic_nGPT_3Step_TimeEmbedding
#SBATCH --time=6:30:00
#SBATCH --output=job_logs/Pythia_Arithmetic_nGPT_3Step_TimeEmbedding_%A.out

cd $HOME/Letting-NNs-Think-Synthetic
. jobs/environment.sh

srun python -m experiment \
    --model-name "EleutherAI/pythia-70m" \
    --dataset arithmetic \
    --finetune-mode full \
    --enable-normalization \
    --use-time-embedding \
    --make-layers-recurrent 2:4 \
    --num-steps 3 \
    --batch-size 2048 \
    --grad-acc-steps 1 \
    --learning-rate 1e-3 \
    --max-hours 6 \
    --max-epochs 1 \
    --use-early-stopping \
    --max-training-steps 2000000 \
    --validate-every-n-steps 1000 \
    --experiment-name Pythia_Arithmetic_nGPT_3Step_TimeEmbedding \
    --save-to-checkpoint Pythia_Arithmetic_nGPT_3Step_TimeEmbedding \
    --enable-logging \
    --project-name letting-nns-think-synthetic

srun python -m experiment \
    --model-name "EleutherAI/pythia-70m" \
    --dataset arithmetic \
    --pretrained \
    --finetune-mode full \
    --enable-normalization \
    --use-time-embedding \
    --make-layers-recurrent 2:4 \
    --num-steps 3 \
    --experiment-name Pythia_Arithmetic_nGPT_3Step_TimeEmbedding_Eval \
    --load-from-checkpoint Pythia_Arithmetic_nGPT_3Step_TimeEmbedding \
    --evaluation-metrics arithmetic \
    --mode evaluate \
    --max-epochs 1 \
    --max-training-steps 1 \
    --eval-batch-size 4096 \
    --enable-logging \
    --project-name letting-nns-think-synthetic
