#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --job-name=Pythia_Arithmetic_nGPT
#SBATCH --time=04:30:00
#SBATCH --output=job_logs/Pythia_Arithmetic_nGPT_%A.out

cd $HOME/Letting-NNs-Think
. jobs/environment.sh

srun python -m experiment \
    --model-name "EleutherAI/pythia-70m" \
    --dataset synthetic_arithmetic_task \
    --finetune-mode full \
    --enable-normalization \
    --batch-size 8192 \
    --grad-acc-steps 1 \
    --learning-rate 3e-5 \
    --max-hours 4 \
    --max-epochs 50 \
    --use-early-stopping \
    --max-training-steps 1000000 \
    --experiment-name Pythia_Arithmetic_nGPT \
    --save-to-checkpoint Pythia_Arithmetic_nGPT \
    --enable-logging \
    --mode train

srun python -m experiment \
    --model-name "EleutherAI/pythia-70m" \
    --dataset synthetic_arithmetic_task \
    --pretrained \
    --finetune-mode full \
    --enable-normalization \
    --experiment-name Pythia_Arithmetic_nGPT_Eval \
    --load-from-checkpoint Pythia_Arithmetic_nGPT \
    --evaluation-metrics arithmetic_task \
    --mode evaluate \
    --max-epochs 1 \
    --max-training-steps 1 \
    --eval-batch-size 8192 \
    --enable-logging
