#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=OneLayerRecurrentTransformer_MiddleLayerFineTuning_GPTNeo_125m_CSQA
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=24:00:00
#SBATCH --output=job_logs/OneLayerRecurrentTransformer_MiddleLayerFineTuning_GPTNeo_CSQA_%A.out

cd $HOME/Letting-NNs-Think

. jobs/OneLayerRecurrentTransformer/GPTNeo_125m/CSQA/MiddleLayerFineTuning.sh
