#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=2
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=2
#SBATCH --job-name=Llama2_Fineweb_nGPT_128Context
#SBATCH --time=3-00:00:00
#SBATCH --output=job_logs/Llama2_Fineweb_nGPT_128Context_%A.out

cd $HOME/Letting-NNs-Think

. jobs/environment.sh

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --dataset fineweb \
  --finetune-mode full \
  --batch-size 128 \
  --grad-acc-steps 1 \
  --seq-length 128 \
  --learning-rate 1e-4 \
  --warmup-steps 36000 \ # 50000
  --initial-lr 3e-6 \
  --validate-every-n-steps 1000 \
  --max-hours 144 \
  --max-training-steps 3000000 \
  --max-epochs 1 \
  --enable-normalization \
  --experiment-name Llama2_Fineweb_nGPT_128Context \
  --save-to-checkpoint Qwen_Fineweb_nGPT_128Context \
  --enable-logging
