#!/bin/bash

#SBATCH --gres=gpu:4
#SBATCH -C A5000
#SBATCH --job-name=Fineweb_nGPT
#SBATCH --ntasks-per-node=4
#SBATCH --time=1-00:00:00
#SBATCH --output=job_logs/Fineweb_nGPT_%A.out

cd $HOME/Letting-NNs-Think

. jobs/environment.sh

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --dataset fineweb \
  --batch-size 8 \
  --enable-normalization \
  --finetune-mode full \
  --learning-rate 1e-4 \
  --warmup-steps 50000 \
  --total-training-steps 400000 \
  --experiment-name Fineweb_nGPT \
  --enable-logging \
  --save-to-checkpoint Fineweb_nGPT

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --dataset gsm8k \
  --batch-size 8 \
  --enable-normalization \
  --finetune-mode full \
  --experiment-name Fineweb_GSM8K_nGPT \
  --enable-logging \
  --load-from-checkpoint Fineweb_nGPT \
  --save-to-checkpoint Fineweb_GSM8K_nGPT

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --mode evaluate \
  --enable-normalization \
  --fine-tune-mode full \
  --evaluation-metrics gsm8k \
  --load-from-checkpoint Fineweb_GSM8K_nGPT \
  --enable-logging \
  --experiment-name Fineweb_GSM8K_nGPT
