#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --job-name=Fineweb_nGPT_Recurrent_3Steps
#SBATCH --time=1-00:00:00
#SBATCH --output=job_logs/Fineweb_nGPT_%A.out

cd $HOME/Letting-NNs-Think

. jobs/environment.sh

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --dataset fineweb \
  --batch-size 8 \
  --enable-normalization \
  --make-layers-recurrent 12:16 \
  --num-steps 3 \
  --finetune-mode full \
  --learning-rate 1e-4 \
  --warmup-steps 30000 \
  --total-training-steps 400000 \
  --experiment-name Fineweb_nGPT_Recurrent_3Steps \
  --enable-logging \
  --save-to-checkpoint Fineweb_nGPT_Recurrent_3Steps

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --dataset gsm8k \
  --batch-size 8 \
  --enable-normalization \
  --make-layers-recurrent 12:16 \
  --num-steps 3 \
  --finetune-mode full \
  --experiment-name Fineweb_GSM8K_nGPT_Recurrent_3Steps \
  --enable-logging \
  --load-from-checkpoint Fineweb_nGPT_Recurrent_3Steps \
  --save-to-checkpoint Fineweb_GSM8K_nGPT_Recurrent_3Steps

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --mode evaluate \
  --enable-normalization \
  --make-layers-recurrent 12:16 \
  --num-steps 3 \
  --finetune-mode full \
  --evaluation-metrics gsm8k \
  --load-from-checkpoint Fineweb_GSM8K_nGPT_Recurrent_3Steps \
  --enable-logging \
  --experiment-name Fineweb_GSM8K_nGPT_Recurrent_3Steps
