#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --job-name=Pythia_Fineweb_nGPT_05step
#SBATCH --time=04:30:00
#SBATCH --output=job_logs/Pythia_Fineweb_nGPT_05Step_%A.out

cd $HOME/Letting-NNs-Think

. jobs/environment.sh

srun python -m experiment \
    --model-name "EleutherAI/pythia-70m" \
    --dataset fineweb \
    --finetune-mode full \
    --enable-normalization \
    --batch-size 64 \
    --grad-acc-steps 4 \
    --learning-rate 3e-4 \
    --warmup-steps 20000 \
    --total-training-steps 4000000 \
    --max-hours 4 \
    --make-layers-recurrent 3 \
    --num-steps 5 \
    --experiment-name Pythia_Fineweb_nGPT_05Step \
    --save-to-checkpoint Pythia_Fineweb_nGPT_05Step \
    --enable-logging
