#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=OneLayerRecurrentTransformer_FullFineTuning_Gemma_2b_Ultrafeedback
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=24:00:00
#SBATCH --output=job_logs/OneLayerRecurrentTransformer_FullFineTuning_Gemma_2b_Ultrafeedback_%A.out

cd $HOME/Letting-NNs-Think

. jobs/OneLayerRecurrentTransformer/Gemma_2b/Ultrafeedback/FullFineTuning.sh
