#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=4
#SBATCH --job-name=FullFineTuning_LastLayerRecurrent_ThreeSteps
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=18
#SBATCH --time=24:00:00
#SBATCH --output=job_logs/FullFineTuning_LastLayerRecurrent_ThreeSteps_%A.out

cd $HOME/Letting-NNs-Think

. jobs/environment.sh

srun python -m experiment \
  --model_name "google/gemma-2-2b" \
  --finetune_layers "all" \
  --no_evaluate \
  --make_layers_recurrent -1 \
  --num_steps 3 \
  --experiment_name LastLayerRecurrent_FullFineTuning_ThreeSteps \
  --save_to_checkpoint LastLayerRecurrent_FullFineTuning_ThreeSteps

srun python -m experiment \
  --model_name "google/gemma-2-2b" \
  --finetune_layers "all" \
  --make_layers_recurrent -1 \
  --num_steps 3 \
  --checkpoint LastLayerRecurrent_FullFineTuning_ThreeSteps \
  --experiment_name LastLayerRecurrent_FullFineTuning_ThreeSteps
