#!/bin/bash

#SBATCH --gres=gpu:4
#SBATCH --ntasks-per-node=4
#SBATCH --job-name=Pythia_Fineweb_nGPT
#SBATCH --time=5-0
#SBATCH --output=job_logs/Pythia_Fineweb_%A.out

cd $HOME/Letting-NNs-Think

. jobs/environment.sh

srun python -m experiment \
    --model-name "EleutherAI/pythia-70m" \
    --dataset fineweb \
    --finetune-mode full \
    --enable-normalization \
    --batch-size 8 \
    --grad-acc-steps 32 \
    --learning-rate 3e-4 \
    --warmup-steps 20000 \
    --total-training-steps 4000000 \
    --max-hours 120 \
    --experiment-name Pythia_Fineweb_nGPT \
    --save-to-checkpoint Pythia_Fineweb_nGPT \
    --enable-logging
