#!/bin/bash

#SBATCH --gres=gpu:4
#SBATCH -C GTX1080Ti
#SBATCH --ntasks-per-node=4
#SBATCH --job-name=Pythia_Fineweb_nGPT
#SBATCH --time=10-0
#SBATCH --output=job_logs/Pythia_Fineweb_nGPT_%A.out

cd $HOME/Letting-NNs-Think

. jobs/environment.sh

srun python -m experiment \
    --model-name "EleutherAI/pythia-70m" \
    --dataset fineweb \
    --finetune-mode full \
    --enable-normalization \
    --batch-size 8 \
    --grad-acc-steps 32 \
    --learning-rate 5e-5 \
    --warmup-steps 50000 \
    --total-training-steps 5000000 \
    --validate-every-n-steps 5000 \
    --max-hours 240 \
    --experiment-name Pythia_Fineweb_nGPT \
    --save-to-checkpoint Pythia_Fineweb_nGPT \
    --enable-logging
