#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=AdaptiveTransformer_LastLayerFineTuning_GPTNeo_125m_Ultrafeedback
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=50:00:00
#SBATCH --output=job_logs/AdaptiveTransformer_LastLayerFineTuning_GPTNeo_Ultrafeedback_%A.out

cd $HOME/Letting-NNs-Think

. jobs/AdaptiveTransformer/GPTNeo_125m/Ultrafeedback/LastLayerFineTuning.sh
