#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --job-name=Pythia_Arithmetic_3Step_TimeEmbedding_LoopedTransformer
#SBATCH --time=4:30:00
#SBATCH --output=job_logs/Pythia_Arithmetic_3Step_TimeEmbedding_LoopedTransformer_%A.out

cd $HOME/Letting-NNs-Think-Synthetic
. jobs/environment.sh

srun python -m experiment \
    --model-name "EleutherAI/pythia-70m" \
    --dataset arithmetic \
    --make-layers-recurrent 0:6 \
    --num-steps 3 \
    --num-runs 3 \
    --seeds 42 43 44 \
    --use-time-embedding \
    --finetune-mode full \
    --batch-size 1024 \
    --grad-acc-steps 1 \
    --learning-rate 3e-4 \
    --max-hours 4 \
    --max-epochs 1 \
    --use-early-stopping \
    --max-training-steps 2000000 \
    --validate-every-n-steps 1000 \
    --experiment-name Pythia_Arithmetic_3Step_TimeEmbedding_LoopedTransformer \
    --save-to-checkpoint Pythia_Arithmetic_3Step_TimeEmbedding_LoopedTransformer \
    --enable-logging \
    --project-name letting-nns-think-synthetic-2

srun python -m experiment \
    --model-name "EleutherAI/pythia-70m" \
    --dataset arithmetic \
    --make-layers-recurrent 0:6 \
    --num-steps 3 \
    --num-runs 3 \
    --seeds 42 43 44 \
    --use-time-embedding \
    --pretrained \
    --finetune-mode full \
    --experiment-name Pythia_Arithmetic_3Step_TimeEmbedding_LoopedTransformer_Eval \
    --load-from-checkpoint Pythia_Arithmetic_3Step_TimeEmbedding_LoopedTransformer \
    --evaluation-metrics arithmetic \
    --mode evaluate \
    --max-epochs 1 \
    --max-training-steps 1 \
    --eval-batch-size 2048 \
    --enable-logging \
    --project-name letting-nns-think-synthetic-2
