#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1
#SBATCH --job-name=GSM8K_1StepEVAL
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=18
#SBATCH --time=30:00:00
#SBATCH --output=job_logs/GSM8K_1Step_Eval_%A.out

cd $HOME/Letting-NNs-Think

. jobs/environment.sh

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --mode evaluate \
  --evaluation-metrics gsm8k \
  --load-from-checkpoint GSM8K_1Step \
  --experiment-name GSM8K_1Step
