#!/bin/bash

#SBATCH --gres=gpu:4
#SBATCH --job-name=GSM8K_3Steps_Eval
#SBATCH --ntasks-per-node=4
#SBATCH --time=30:00:00
#SBATCH --output=job_logs/GSM8K_3Steps_Eval_%A.out

cd $HOME/Letting-NNs-Think

. jobs/environment.sh

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --make-layers-recurrent 11 \
  --num-steps 3 \
  --mode evaluate \
  --evaluation-metrics gsm8k \
  --load_from_checkpoint GSM8K_3Step \
  --experiment-name GSM8K_3Step
