#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=4:00:00
#SBATCH --job-name=UninteruptedTransformer-FullLora-Untied-Recurrent-1StepTEST
#SBATCH --output=job_logs/Uninterrupted-Transformer-FullLora-Untied-Recurrent-1Step-TEST-%A.out

cd $HOME/Letting-NNs-Think

. jobs/environment.sh

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --dataset gsm8k \
  --max-epochs 1 \
  --batch-size 16 \
  --learning-rate 1e-3 \
  --make-uninterrupted \
  --uninterrupted-recurrence-depth 1 \
  --finetune-mode 'lmhead_lora' \
  --experiment-name UninterruptedTransformerFullLoraUntied1StepTEST \
  --save-to-checkpoint UninterruptedTransformerFullLoraUntied1StepTEST \
  --uninterrupted-loss-weight 0.0

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --mode evaluate \
  --finetune-mode 'lmhead_lora' \
  --evaluation-metrics gsm8k \
  --load-from-checkpoint UninterruptedTransformerFullLoraUntied1StepTEST \
  --experiment-name UninterruptedTransformerFullLoraUntied1StepTEST 
