#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --job-name=GSM8K_3Steps_TimeEmbedding_RandomIntermediateSupervision
#SBATCH --ntasks-per-node=1
#SBATCH --time=4:00:00
#SBATCH --output=job_logs/GSM8K_3Steps_TimeEmbedding_RandomIntSupervision_%A.out

cd $HOME/Letting-NNs-Think

. jobs/environment.sh

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --dataset gsm8k \
  --use-time-embedding \
  --use-random-intermediate-supervision \
  --make-layers-recurrent -1 \
  --num-steps 3 \
  --batch-size 8 \
  --experiment-name GSM8K_3Step_TimeEmbedding_RandomIntermediateSupervision \
  --enable-logging \
  --save-to-checkpoint GSM8K_3Step_TimeEmbedding_RandomIntermediateSupervision

srun python -m experiment \
  --model-name "google/gemma-2-2b" \
  --make-layers-recurrent -1 \
  --use-time-embedding \
  --use-random-intermediate-supervision \
  --num-steps 3 \
  --mode evaluate \
  --evaluation-metrics gsm8k \
  --load-from-checkpoint GSM8K_3Step_TimeEmbedding_RandomIntermediateSupervision \
  --enable-logging \
  --experiment-name GSM8K_3Step_TimeEmbedding_RandomIntermediateSupervision
